controller_list:
  - name: fake_uwrt_arm_controller
    joints:
      - arm_base_turntable_joint
      - arm_shoulder_joint
      - arm_elbow_joint
      - arm_wrist_roll_joint
      - arm_wrist_pitch_joint
  - name: fake_uwrt_arm_gripper_controller
    joints:
      - arm_wrist_pitch_joint
