# MoveIt-specific simulation settings
ros_control_namespace: "/"
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_base_turntable_joint
    - arm_shoulder_joint
    - arm_elbow_joint
    - arm_wrist_roll_joint
    - arm_wrist_pitch_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_trajectory_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - arm_base_turntable_joint
      - arm_shoulder_joint
      - arm_elbow_joint
      - arm_wrist_roll_joint
      - arm_wrist_pitch_joint
    gains:
      arm_shoulder_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_elbow_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_wrist_roll_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_wrist_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_base_turntable_joint
    - arm_shoulder_joint
    - arm_elbow_joint
    - arm_wrist_roll_joint
    - arm_wrist_pitch_joint
  gains:
    arm_shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
