# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_base_turntable_joint
    - arm_shoulder_joint
    - arm_shoulder_bicep_joint
    - arm_elbow_joint
    - arm_wrist_roll_joint
    - arm_wrist_pitch_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list: []  # Not sure why this is required

arm_cartesian_controller:
 type: velocity_controllers/UWRTCartesianController
 root_name: world
 tip_name: arm_claw_link
 joints:
    - arm_base_turntable_joint
    - arm_shoulder_joint
    - arm_shoulder_bicep_joint
    - arm_elbow_joint
    - arm_wrist_roll_joint
    - arm_wrist_pitch_joint